### PR TITLE
Adding iocStats to be optionally loaded for reboot functionality

### PR DESCRIPTION
**Pull request by oksanagit**
I have been asked to add the reboot functionality to the IOC. It could be useful to others. Also, updated PREFIX to the generic name.

### CODE REVIEW

**Comment by newville** [comment]
@oksanagit Thanks -- I guess iocStats is compiled in but not loaded.  Should we add that for all the IOCs?

**Comment by MarkRivers** [comment]
Is there a commonPlugins.cmd that gets executed? You can put iocStats in there.

**Comment by newville** [comment]
@oksanagit @MarkRivers Yes to both -- if you put this is in  "common/SetMainValues.cmd"  (https://github.com/epics-modules/xspress3/blob/master/iocs/xspress3IOC/iocBoot/common/SetMainValues.cmd) that would be great.

**Comment by oksanagit** [comment]
@newville , It seems that adding lading iocStats module would make more sense in DefineXSP3Driver.cmd. SetMainValues.cmd configure the PVs' initial values. Please confirm.

**Comment by MarkRivers** [comment]
I think @oksanagit is correct, because SetMainValues.cmd is called after iocInit.  You need to add it to a file that is called before iocInit.

**Comment by newville** [comment]
@oksanagit Ah, thanks, good catch, yes `DefineXSP3Driver.cmd` makes more sense.

**Comment by newville** [comment]
replaced by #36

**Pull request closed without merging**
