### PR TITLE
Unify and simplify the Xspress3 IOCs from APS and QD

### PR DESCRIPTION
**Pull request by CasperVector**
What is done:
* IOCs are unified; the user now only needs to tune `${XSP3CHANS}` and `${XSP3CARDS}` in `st.cmd`.
* `.db` files are fully simplified; features from both branches are combined.
  (The C++ layer of the APS branch is taken; other interfaces of the APS branch are also preferred.)
* The code generator is minified (see `iocs/xspress3IOC/iocBoot/iocXspress3/xsp3-chan.sh`).
* The build system is made fully compliant with areaDetector conventions.
* Documentation from both branches are unified into `documentation/manual.html`, with a PV comparison table.

What is not done:
* Cumulative spectra are not yet supported; some DB links are needed, but are surely doable with the code generator.
* NDPluginAttribute is not yet used, so we can only access the latest SCA RBVs in multi-frame acquision.
  (The `.xml` file is surely doable with the code generator, but I *think* there should be a simpler way to promote 0-dimensional values into arrays for multi-frame acquision.)
* OPIs are untouched; I am not familiar with OPIs, and care needs to be taken for the code generator to make OPIs happy.
* Latest changes from QD are [undisclosed](https://gitlab.com/qd-xspress3/epics) and are therefore not merged.
  (IOCs in latest prebuilt RPMs from QD output strings containing `xsp4` etc.)
* A small paper is currently in progress to describe the techniques used in the refactoring.

### CODE REVIEW

**Comment by newville** [comment]
@CasperVector Thanks - that looks like a lot of work and should be very useful.  But it is also kind of a lot of changes to review as a single changeset, especially coming sort of out of the blue and without any discussion or issues raised to motivate the work.  100+ commits, touching 400+ files is kind of a lot to expect to be merged. 

Is it OK to view this PR as a start of a conversation about merging in all these changes?  If so, would you be willing to break this into a few separate changesets? A couple of suggestions for how to do this to make it easier to merge into this branch would be:
   a) make separate PRs for the changes to the documentation and maybe another separate PR for the upgraded API. 
   b) it's fine to *add* an IOC, especially if it can be independent of the number of detector elements (I'm not sure how everything can actually be fully modular, especially the XML attributes file).  But, why erase existing IOC folders that are actually in use now?  I think we could be persuaded to change, but it is probably better to deprecate the other IOC directories before removing them.

I think I don't understand all of your "what is not done" points.  Cumulative spectra are available and NDAttributes are used, but maybe you mean something different for these?

**Comment by CasperVector** [comment]
The changeset appears huge because of technical reasons with both git.  The current version of the changeset boils down to 17 commits when viewed from the `APS_old` branch (equivalent to the `no_erase` branch in this repository as of now):
* 1a84b3e6 to 4e51fd64: 5 commits cherry-picked from the QD branch to merge peripheral modifications.
* 1cd766bb to 18b07e29: 3 commits to make the build system more areaDetector-conformant.
* 4a08a2c4 to 742817ab: 4 commits to to unify the IOCs and the DBs that supported them.
* 30c52587 to d306f335: 2 commits to remove ROI code in C++ and merge DB features from QD.
* 35bcc0e7: 1 commit to merge the `QD` and `APS` branches (not `QD_old` and `APS_old`), just merging 4 files from QD.
* d9bf5a0e to 59ff3112: 2 commits to merge and restructure the documentation.

The 100+ commits shown on the github interface, or equivalently when runnning `git log APS_old..master` in my repository, come from the `QD` branch, which has seen much more commits since `QD_old`, which are however in essence similar to the commits above. If `35bcc0e7` was replaced with a commit that just had introduced the same 4 files from QD without using `git merge`, you would only see 17 commits.  Nevertheless, I do not want to do said replacement just to appease git, because the changes provided, in relatively small steps, bases for commits d1195c55 of `QD` and 2d5c3069 of `APS` (as of now; the commit IDs have changed many times due to `git rebase`, in order to accommodate for necessary adjustments discovered during debugging or code review, while keeping the changeset minimal), which would otherwise seem like emerging from nowhere with zero motivation.  (The two branches also provided motivation for each other; for commit d1195c55 and 2d5c3069, I mainly learned from the QD branch because the code is more mechanically regular.)

I am fully willing to cooperate with upstream to find a least intrusive way to merge the changes, and I agree that a smooth transition path will be highly desirable.  Simply keeping the old `ioc*` directories would be very confusing to both users and developers, because their counterparts in the QD branch would also need to be kept; instead I suggest that the APS and QD IOC directories get merged into `iocXsp3APS` and `iocXsp3QD`, respectively.  The XML files can certainly be machine-generated: just provide a header, a footer and a body file with `${CHAN}` and `${ADDR}` ready to be substituted, and let `xsp3-chan.sh` do the substitution and concatenation.

I know cumulative spectra and SCA RBV arrays for multi-frame acquision are done in both APS and QD branches.  They are not done in my branch as of now because:
* Generating XML files with `xsp3-chan.sh` is surely doable, as is outlined above; I just find the C++/XML/NDPluginAttribute way to promote 0-dimensional values into arrays quite a "roundabout", and wonder whether there is a simpler way to do it.
* I did not (and still do not quite) have time to investigate `xspress3_*.template`, so I focused on the featured required by my colleagues. However, the same functionalities are surely doable in the refactored framework, and might perhaps even be a little simpler to implement.

I will certainly be very glad if you would like to add the missing pieces by yourself, which will also help you to understand the refactored codebase :)

**Comment by newville** [comment]
@CasperVector Thanks.   Well, OK, it's more like 17 commits (or group of commits) instead of 100.  It would still be helpful to merge them one at a time or, a perhaps a few at a time.  Do you think that is possible?

**Comment by CasperVector** [comment]
I personally do not mind splitting the changeset into a few groups, but the only way to I find to implement it on github is submitting pull requests one by one, each after the previous one has been merged, which seems obviously ugly to me :(

More importantly, what is your opinion on the treatment of the `ioc*` directories under `iocBoot`? if you find the `iocXsp3APS`/`iocXsp3QD` plan OK, I will take my spare time to create a new changeset that implements it, and then submit new PR(s) after we agree upon a way to group the changeset.

`git push -f` might occur on the `master` branch on my side, but the current version of the `master` branch will be kept in a new branch for future reference; future PRs will be made to merge non-`master` branches.

**Comment by newville** [comment]
@CasperVector 
> I personally do not mind splitting the changeset into a few groups, but the only way to I find to implement it on github is submitting pull requests one by one, each after the previous one has been merged, which seems obviously ugly to me :(

Thanks. I would not blame github for this.  I would like to see these changes examined, reviewed, maybe modified, and then accepted as smaller sets (maybe 5 to 20, I'm not really sure) based on logical changes to the code.  That is, I think it is pretty common to not want to merge huge changes but to prefer to merge smaller changes and make sure things don't break as that happens.  

Updating the doxygen docs is completely orthogonal to updating the ioc boot directories -- please separate those changes into separate PRs so that later on we'll be able to identify PRs logically not "massive dump of changes to many parts of the code base". That is, please make more, smaller PRs based on topics.

> More importantly, what is your opinion on the treatment of the ioc* directories under iocBoot? 
> if you find the iocXsp3APS/iocXsp3QD plan OK,

I don't know.  We'll review that when we come to it.  For sure, removing existing, working (and in production!) ioc boot directories is almost certainly going to not be accepted.  It's certainly fine to add more ioc boot directories, even with very different ways of building st.cmd, etc.  That does no harm.  

I don't know that a single IOC boot directory can easily accommodate Xspress systems with the number of elements set at run time.  I think that would need to generate an XML file that gets loaded at boot time (and before iocInit, I believe). I'm not sure that's possible, though perhaps a bash script could do that.

I would not label any of them as "APS" -- that's both too broad and too specific. Generally, we're trying to provide examples, and/or exact ioc boot directories in production. 


> I will take my spare time to create a new changeset that implements it, and then submit new PR(s) after we agree upon a way to group the changeset.

I might suggest starting with the docs, updates to build system, updates from shared lib/interface, updates to driver, and updates to iocs.  That might be most of the changes, and then we can see where it's at.

**Comment by CasperVector** [comment]
The changeset has already been carefully split into commits that are mostly either automated changes reproducible with a few lines of commands (for less trivial changes, I would put the script in the body of the commit message), or small manual changes (at most a few dozens of lines; `manual.html` is an exception, but it is pure documentation).

The ancillary files `xsp3-${XSP3CHANS}ch.*` and calibration files certainly need to be generated, due to the limitation of the iocsh language, as has been outlined in `manual.html`; that is already be close to the theoretical limit we can achieve in compression of the code generator, and other than that everything else can be done with EPICS alone.

By the `iocXsp3APS`/`iocXsp3QD` plan, I mean gathering all APS/QD `ioc*` contents into `iocXsp3APS`/`iocXsp3QD`, but without change in any aspect of usage other than using a different path for the `*.cmd` startup scripts if they have been used as is.  I strongly dislike the idea of merging directories like `ioc4Channel` and `ioc_4Channel` into the same `iocBoot` directory, which would be a best way to confuse unfamiliar users.

I will open a new branch for the changes needed on my side, which may take 1~2 months; I suggest a new branch on your side as well for the PRs that will come.  I also recommend to merge the commits in the current order, because earlier commits provide bases for later ones: for example, without everything else before, the details in `manual.html` would not have been settled down.

**Comment by newville** [comment]
@CasperVector 

I think we're not really understanding each other and mostly talking past each other. 

> The changeset has already been carefully organised as commits that are mostly either automated changes reproducible with a few lines of commands (for less trivial changes, I would put the script in the body of the commit message), or small manual changes (at most a few dozens of lines; manual.html is an exception, but it is pure documentation).

This PR is enormous and will break the current production code because it erases files that are actually used in production. 

It came completely out of the blue, without context, and without warning from someone who has no history with this code.   Do you work with or for Quantum Detectors?  At some light source?  I don't know.

Really, we are not going to merge all this in one PR.  This is mature code used in production.  We make incremental improvements, identifying shortcomings and fixing them while being careful to not break anything along the way.  So, huge PRs that touch many aspects of the code are not what we need or want.
Submit smaller patches that solve one issue at a time.

> The ancillary files xsp3-${XSP3CHANS}ch.* and calibration files certainly need to be generated, as has been outlined in manual.html, due to the limitation of the iocsh language; that is already be close to the theoretical limit we can achieve in compression of the code generator, and other than that everything else can be done with EPICS alone.
>
> By the iocXsp3APS/iocXsp3QD plan, I mean gathering all APS/QD ioc* contents into iocXsp3APS/iocXsp3QD, but without change in any aspect of usage other than using a different path for the *.cmd startup scripts if they have been used as is. I strongly dislike the idea of merging directories like ioc4Channel and ioc_4Channel into the same iocBoot directory, which would be a best way to confuse unfamiliar users.

A PR that deletes production iocBoot folders won't get merged. It won't even get much of a reading.   So, I don't really know what you are talking about.  Create an Issue describing the problem you are trying to avoid.

**Comment by CasperVector** [comment]
I did not propose to merge this as a whole, except in the initial post when I had not yet got your opinions. What I mean is to break the changeset into groups, but still keeping the original order and a similar commit structure: 1a84b3e to 4e51fd6, 1cd766b to 18b07e2, etc; the actual commit IDs will change of course, because a transition plan needs to be implemented.  By the way, `ioc4Channel` comes from the QD branch, and `ioc_4Channel` comes from the APS branch as you probably already know; I do not think new users will be able to clearly remember which comes from where.

When I said "without change in any aspect of usage other than using a different path for the `*.cmd` startup scripts, if they have been used as is", I meant it; or there will not be a paper to describe the techniques, which has incidentally been successfully tested in around 10 refactoring projects related or unrelated to EPICS.  This does not conflicts with "make incremental improvements, identifying shortcomings and fixing them while being careful to not break anything along the way" at all.  The refactored codebase have also been tested on real hardware, although certainly not in a way that exhausts every possibility out there, which is part of why I dare to submit this PR; however, I can certainly wait until the paper is put online, perhaps on arXiv or so.

**Comment by newville** [comment]
@CasperVector 
> I did not propose to merge this as a whole, except in the initial post when I had not yet got your opinions. What I mean is to break the changeset into groups, but still keeping the original order and a similar commit structure: 1a84b3e to 4e51fd6, 1cd766b to 18b07e2,  etc; the actual commit IDs will change of course, because a transition plan needs to be implemented.

Each Pull request should solve an identified problem in the existing codebase.  Maybe your commit history does that, maybe not.

> By the way, ioc4Channel/ioc4ChannelMini come from the QD branch, and ioc_4Channel comes from the APS branch as you probably already know; I do not think new users will be able to clearly remember which comes from where.

This repository does not have a branch labeled QD.  I have no idea what you are talking about.

> When I said "without change in any aspect of usage other than using a different path for the *.cmd startup scripts, if they have been used as is", I meant it; or there will not be a paper to describe the techniques, which have incidentally been successfully tested in around 10 refactoring projects related or unrelated to EPICS. 

How do you test? What do you test?   I have no idea what you mean by "a paper to describe the techniques".

> This does not conflict with "make incremental improvements, identifying shortcomings and fixing them while being careful to not break anything along the way" at all; the refactored codebase have also been tested on real hardware, although certainly not in a way that exhausts every possibility. 

You deliberately erased our production iocboot folders.  So I am pretty sure you didn't test those.

> This is part of why I dare to submit this PR; however, I can certainly wait until the paper is put online, perhaps on arXiv or so.

No idea what this means. 

I am closing this PR.   Again, please submit smaller PRs that solve one clearly defined issue at a time.

**Comment by CasperVector** [comment]
The tested projects include [quite](https://gitea.com/CasperVector/reagent) [a](https://github.com/cjdelisle/cjdns/pull/1221) [few](https://github.com/CasperVector/npreal2) open-source ones, just to name those which are relatively interesting.  That you seemingly cannot come up with ways to analyse the correctness of large commits, like [comparing](https://github.com/CasperVector/cjdns/commit/79a60b95#diff-eaaa0a2eb107ef8833be39977cd39331596829445c0f49529a2f3a7eebe5f977) intermediate code generated by the compiler, does not imply I could not.  That you have no idea about the possibility of a systematic treatment of the techniques does not imply I had no idea either.

The legacy codebase in the version above of the changeset was certainly not tested; the behavioural equivalence between it and the refactored codebase was, or the PV comparison table in `manual.html` would not have been existed.  And as you deliberately ignore my promise to move to `iocXsp3APS`/`iocXsp3QD` etc coexisting with `iocXspress3`, I fulfilled my promise.  15 hours of coding, including 3 hours of testing where the `iocXsp3APS` setup involved passed with one shot and proved to behave the same way as the legacy codebase, except for [a](https://github.com/CasperVector/ADXspress3/blob/0315abbc/iocs/xspress3IOC/xspress3App/Db/Makefile) [bug](https://github.com/epics-modules/xspress3/blob/919f07de/xspress3App/Db/Makefile) buried in copy and paste on the legacy side.

Proposing for pull in your repository has nothing to do with my personal interest; encapsuled in this pull "request" was an *offer* to avoid creating more [fragmentation](https://xkcd.com/927/) in the community.  My interest is in enabling both users and developers to minimise workload, and I cherish any feasibility to simplify a sizable software module by an order of magnitude or more without sacrificing functionality, for which I am willing to risk some [bugs](https://github.com/CasperVector/ADXspress3/blob/0315abbc/README.md#compatibility) that slip through testing.  Well, in the case of ADXspress3 I also "risked" finding a few [bugs](https://github.com/CasperVector/ADXspress3/commit/004d67c1) in the "carefully" maintained legacy codebase.

But this reply is not an attempt to request reconsideration.  I thought you would at least be considerate enough for users of the QD [IOCs](https://github.com/quantumdetectors/xspress3-epics) to also allow backward compatibility for them, which has of course been falsified by your ludicrously cheap word play with "QD branch".  For record-keeping purposes, the version above of the changeset has been archived in the [`patchset-aps25`](https://github.com/CasperVector/ADXspress3/tree/patchset-aps25) branch in my repository.  Happy playing with your boilerplate code; `\bye`.

**Comment by mdmoo1978** [comment]
As the person who move the xpress3 code from area detector 1.x to 2.x, Casper, I want to make it very clear that Quantum Detectors had no interest in move the code forward and basically said “go away, we don’t care”. I was left completely to my own do make this move with little help from anyone at APS or QD. So I understand your unhappiness, but the fact is that QD gave up any backwards compatibility the day they told me to go away. 

Now, since I have no interests in this anymore, thank you for find a copy and paste bug and any other bugs. I have no idea who your agreement to do 15 hour of coding and testing was to, but if it was Roger at QD, tell him to call me and we can settle things. Matt Newville has been doing a great job of trying to keep this code base moving forward, despite the fact that I had no idea what I was doing at the time of converting, but knew it had to be done. So Casper if you want to be mad at someone about how the code base is, choose me and let it go.

Cheers,
Matt Moore
Former APS Detector Group Employee

**Comment by newville** [comment]
@CasperVector 
> The tested projects include quite a few open-source ones, just to name those which are relatively interesting. 

Sorry, but does that have any relation with the code here?   I cannot tell.
 
> That you seemingly cannot come up with ways to analyse the correctness of large commits, like comparing intermediate code generated by the compiler, does not imply I could not. That you have no idea about the possibility of a systematic treatment of the techniques does not imply I had no idea either.

I agree that my inability to analyze the correctness of large commits does not mean that it is impossible.  But, strictly speaking, correctness is actually not the only consideration here.  Comprehensibility is also important if, say, we want to continue developing the code.  

I'm saying we would like to see smaller PRs that focus on solving one stated problem at a time.  A huge dump of hundreds of commits, changing hundreds of files is just not something we can review.   We're trying to keep this code production-ready for multiple installations.  We're also trying to improve build and deployment scripts, and make sure that people using the AD19 version of the Xspress3 code have an easy transition (it won't be without some changes).  You can look at other PRs and Issues here for some examples.

> The legacy codebase in the version above of the changeset was certainly not tested; 

Yes, epics drivers and areaDetector behaviors are hard to thoroughly test without dedicated testing hardware, and those tests are hard to automate.  Just the sheer variety of what can go into an `st.cmd` script makes, testing epics iocs very challenging.  The only Xspress3 that I have regular access to is in production.  Most of the people who are using or trying to use this code are in the same position.   So, we go slowly and test our use-cases when we can.  And this is part of why we are reluctant to accept enormous code changes touchy several aspects of the code, and why we are very reluctant to (honestly, just not going to) have production iocboot directories removed. 

> the behavioural equivalence between it and the refactored codebase was, or the PV comparison table in manual.html would not have been existed. 

I don't know what that means.  What manual.html?   Again, if you want us to carefully review your PR, you will have to make smaller PRs that solve one identified problem at a time. 

> And as you deliberately ignore my promise to move to iocXsp3APS/iocXsp3QD etc coexisting with iocXspress3, 

No, I did not.

> I fulfilled my promise. 15 hours of coding, including 3 hours of testing where the iocXsp3APS setup involved passed with one shot and proved to behave the same way as the legacy codebase, except for a bug buried in copy and paste on the legacy side.

What I am saying is that *we* did not test this code with our systems and ioc setups.  We have not done that because we just are not going to merge in this large of a set of changes.  I completely understand that it may very well work for you. 

> Proposing for pull in your repository has nothing to do with my personal interest; encapsuled in this pull "request" was an offer to avoid creating more fragmentation in the community. My interest is in enabling both users and developers to minimise workload, and I cherish any feasibility to simplify a sizable software module by an order of magnitude or more without sacrificing functionality, for which I am willing to risk some bugs that slip through testing. Well, in the case of ADXspress3 I also "risked" finding a few bugs in the "carefully" maintained legacy codebase.

We don't really know what QD or DLS or anyone might be doing. Fragmentation is unfortunate and we've tried to work with as many folks as possible. As Matt Moore said, this codebase started as a move from areaDetector 1.9 to areaDetector 2, more than 5 years ago. It's now at areaDetector 3.  We've tried to merge codes with folks at QD and DLS in the past.  We're working out in the open, in the epics-modules project, and trying to work with folks at many facilities.   Again, you can check earlier Issues, PRs, and code history here.  We're always open to new contributions and improvements.   That's actually different from "we'll accept any changes someone may want to make", but we're open to having discussions about such changes.  Again, making PRs that solve one identified problem at a time is definitely the way to go.   Sorry, but huge dumps are just not something we have time for. 

> But this reply is not an attempt to request reconsideration. I thought you would at least be considerate enough for users of the QD IOCs to also allow backward compatibility for them, which has of course been falsified by your ludicrously cheap word play with "QD branch". 

Sorry, but I do not know what QD branch you are talking about.  Is that something in your fork or from some other repository?  Honestly, I don't know what other codes might be out there...

> For record-keeping purposes, the version above of the changeset has been archived in the patchset-aps25 branch in my repository. Happy playing with your boilerplate code; \bye.

Do you mean you want us to read code in different development branches in your repo?  I don't think we have time for that, certainly not unless you give us very explicit instructions of what to look at.   

Again, all we're asking is that you make smaller PRs that solve one identified problem at a time.  I'm not entirely sure why that request is causing so much discussion, but it's becoming worrisome.

**Comment by CasperVector** [comment]
So I think we had serious mutual misunderstandings, which could have been at least cut in half if you had said early that references outside this repository should be made with an explicit link.  Anyway, let me attempt to express what I mean once more, for better or worse.  I am not from QD or DLS, but the small list of project I gave above should have shown that I am not a random stranger wanting to sell you untested snakeoil.  As I said, I am working on a (more or less) systematic exposition of the refactoring techniques I use; and I do not want to make this discussion a dissertation, so I only give some of the key points.

Given a certain codebase, its refactoring has two important factors: the destination and the path to it.  I want both to be as simple as is reasonable ("comprehensibility"), because that is the only way to reduce bugs ("correctness"); this is why I emphasise that the commits are "mostly either automated changes reproducible with a few lines of commands or small manual changes".  And given the requirement of backward compatibility with both [CARS](https://github.com/epics-modules/xspress3/tree/cc511b1e/iocs/xspress3IOC/iocBoot) (previously misattributed to APS) and [QD](https://github.com/CasperVector/ADXspress3/tree/4cceb49a/iocs/xspress3IOC/iocBoot) (there were also [`iocexample4ChannelMini`](https://github.com/CasperVector/ADXspress3/commit/afcaaa13) etc) drivers, and to avoid confusing new users, I made the [`iocXsp3CARS`/`iocXsp3QD`](https://github.com/CasperVector/ADXspress3/tree/v20210917/iocs/xspress3IOC/iocBoot) directory layout.

The QD parts in ADXspress3 have been adapted with minimal changes just enough to make `iocXsp3QD*` comfortably comparable with the official QD driver.  When I did the tests using my colleague's Xspress3 control box, I put the EPICS/synApps/ADXspress3 tuple in a directory tree that does not conflict with the QD files.  Then I compared the behaviours of `iocXsp3QD` and the QD driver, and then the behaviours of `iocXspress3` and `iocXsp3QD`, all with the same `${XSP3CARDS}`/`${XSP3CHANS}` setup.  I also compared the behaviours of `iocXsp3APS` and a separately compiled CARS driver, and then the behaviours of `iocXspress3` and `iocXsp3APS`; I do not understand why you did not consider something similar, which I think is the most natural yet unintrusive way to do the tests.  Incidentally, I have just [finished](https://github.com/CasperVector/ADXspress3/tree/v20210917) adding support for NDPluginAttribute and cumulative spectra to `iocXspress3`; now it should be fully [functional](https://github.com/CasperVector/ADXspress3/blob/v20210917/documentation/manual.html), up to hidden bugs.

Speaking of "erasing" existing `ioc*` directories, I do not really find simple [renaming](https://github.com/CasperVector/ADXspress3/commit/103d1585) of files used and substitution of corresponding references harmful; the really [erased](https://github.com/CasperVector/ADXspress3/commit/72166d3f) files are either "attic" files or byte-by-byte replicas of files already put into `iocXsp3CARS*`.  And again regarding big changes, if you find a change in a file acceptable, why would you not do it across similar files?  As a beamline-control personnel, I fully understand the importance of feedback; I would surely limit the changes to where they are really needed, and check the correctness of the changes with the help of automation utilities.

**Comment by newville** [comment]
@CasperVector I admit that I am not at all optimistic about this.   Of course, if you want anyone to know what you are talking about, you would have to give details.  I don't think anyone is going to be reading branches of your fork other than the one you have requested to be merged. 

This PR has around 100 commits and changes more than 400 files.  It removes files and directories that I and other people are really using in production.   There is just no possibility that this PR as it currently stands is going to get merged.   I have not even looked at the other changes you have made and really have no idea what you are talking about with your proposed changes to the iocboot folders:  I have not looked at these because the set of changes is simply too big to fully review and I know that it does break production usage.  Maybe the reorganization is good, maybe not -- I have no opinion (maybe "yet") except this: don't remove production iocboot directories until lond after we have all agreed.

As I have said every single time I have written here, please make smaller PRs that focus on one issue at a time.  Changes to source driver, build system, documentation, and iocboot directories can all be separated, at least mostly.  Please try to do that, again, identifying and solving one issue at a time.

It is worrisome that you seem to not understand this request and continue to focus on the details of this PR and the changes to the iocboot directories.

**Comment by CasperVector** [comment]
I said multiple times that I do not request the merge of the changeset (whether [`patchset-aps25`](https://github.com/CasperVector/ADXspress3/tree/patchset-aps25), [`v20210917`](https://github.com/CasperVector/ADXspress3/tree/20210917) or whatever version) in its entirety.  However, in order to reduce the Kolmogorov complexity of the changeset, there is logical correlation between the commits (or set of PRs in case we finally reach an agreement).  The easiest way to understand them is to grasp the big picture first, and then understand the details; which is why I am still here, because the big picture needs to be agreed upon.

I know your stressed the `ioc*` issues multiple times, and I completely agree that the removal needs to be discussed.  I have repeatedly provided reasons why I insist on the `iocXsp3CARS`/`iocXsp3QD` plan, and I have given a non-intrusive testing plan for it which I have used on a real Xspress3 control box; neither of which you directly responded to.  You want more details, which I will give in my paper; and I am completely OK with this conversation in its current status before the paper gets online.

**Comment by newville** [comment]
@CasperVector 
> I said multiple times that I do not request the merge of the changeset (whether patchset-aps25, v20210917 or whatever version) in its entirety. However, in order to reduce the Kolmogorov complexity of the changeset, there is logical correlation between the commits (or set of PRs in case we finally reach an agreement). The easiest way to understand them is to grasp the big picture first, and then understand the details; which is why I am still here, because the big picture needs to be agreed upon.

I have no idea what your various branches include.  

The big picture is that we have working code that is used in production at several beamlines (and, we're hoping, more) here in the `master` branch of the epics-modules/xspress3 repository.   We're happy to have improvements and bug fixes.   All such changes are going to be incremental changes to the existing master branch that solve a single and clearly-stated issue, possibly described in a GitHub Issue in this repo, or well described in the description of the PR.   If you want your code merged here, that is the big picture that has been agreed upon. 

This is why I have consistently asked that you make smaller PRs that target a specific problem or area of improvement. 

> I know your stressed the ioc* issue multiple times, and I completely agree that the removal needs to be discussed. I have repeatedly provided reasons why I insist on the iocXsp3CARS/iocXsp3QD plan, 

Well, certainly as done in this PR, it is not acceptable.  I have no idea what other plans or ideas you might have (hint: submit smaller PRs that solve individual problems).  I don't really get why there should be separate "CARS" and/or "QD" iocboot directories, but I haven't looked into your organization in any detail beyond "it deletes in-production folders".  In the master branch, we have tried to consolidate so that there are boot directories for a variety of detectors, with the idea that these can be used at any facility.   They are used at CARS, other APS, and NSLS2 beamlines.  Lots of folks would use this with a Hitachi ME-4 or ME-7 detector, or other 4- or 7-channel detectors.  I don't really understand why we can't have one iocboot folder for each of those.

In any case, if you want an alternative way to organize iocboot folders, *add* those without *deleting* existing ones.  If your organization is easier for everyone, we'll be able to adopt that without breaking existing installations.  If that is the case, maybe we'll eventually remove some of the unused ones.

> and I have given a non-intrusive testing plan for it which I have used on a real Xspress3 control box; neither of which you directly responded to. 

I have no response because I have absolutely no idea what you are talking about.

> You want more details, which I will give in my paper; and I am completely OK with this conversation in its current status before the paper gets online.

I have no idea what that is.

Again, please make smaller, targeted PRs.   I am now done discussing this PR.

**Comment by CasperVector** [comment]
Well I see. I guess we now both fully recognise that you do not want to try or understand any possibility that involves the removal of directories including `ioc_4Channel`/`iocDualMini_4Channel`/`iocGSECARS-4Channel`/`iocxspress3-4Channel`, even if the content is just moved elsewhere with the promise that they would work like before, and at least kept the promise during some kind of tests.  It is, for whatever reason, your policy.  (@mdmoo1978, thanks for your kind words; the situation is really similar.)

I made a plan that enables previous users of both the official QD version and the CARS version in this repository to trivially compare the functionality of `iocXspress3` with actually working emulation of the version they previously use, where the soundness of the emulation itself can also be trivially tested.  The plan has been tried on real hardware, and has proved to reveal actual bugs; it also reduces the difficulty people can have when trying to choose an `ioc*` directory for use.

The problem is that your policy is strictly against some goals of my plan; but now given the unwillingness to compromise on both sides, I find it worth risking community fragmentation for a long-term test of maintenance.  As has just been said, users now have the choice to easily use the emulation as a middle ground for testing before trying `iocXspress3` in production.  I am perfectly fine with my repository existing as a separate fork.  So problem solved, and I am also done; bravo, open source.

**Comment by mdmoo1978** [comment]
Casper,

Can I ask what spurred on these changes? Did someone hire you to do it? Is it part of some research you are doing? Did QD ask you to look into this?

Matt

**Comment by CasperVector** [comment]
No, nobody asked for this; I am indeed hired at a facility, but this is a spontaneous project.  The reason is enthusiasm ("I cherish any feasibility to simplify a sizable software module by an order of magnitude or more without sacrificing functionality"), plus the confidence that I can really do much, better than people before.  Of course, a first pre-condition is that the code is useful, even if not minimalist in its original form.

**Comment by mdmoo1978** [comment]
As a reminder to all parties, I have no horse in this game anymore, since I haven’t worked on these systems in almost six years.  

The difference between your wholesale changes and mine are that QD was not interested in moving code forward to AD2 and as the head of the APS detector pool (at the time) I was responsible for making our equipment user friendly. My changes might not have been quality, but no one was trying to make this change at the time and we had high quality equipment sitting around because of the software. The jump to AD2 was a major change and required reorganization of the whole build. Now that was years ago and since then things have continued to move forward. I think the issue with how you have approached this is the lack of communication from the beginning.

Matt is trying to keep changes small to better know where bugs occurred and better address them. I know you have no real interest in breaking this up and explaining the pieces, but I think unless you can something along this line your code (with what might be huge improvements) will never make it into master and that might be as bigger a disservice to the community as not make the changes in the first place. Please consider taking some time (doesn’t need to be right now) to make these steps. 

Matt

**Comment by CasperVector** [comment]
Actually I do have interest in explaining the changes -- that will be in the paper; but I am afraid the fragmentation will be pitifully unavoidable unless the no-`ioc*`-removal policy is gone.  The `iocXsp3CARS`/`iocXsp3QD` plan enables previous users of both branches to trivially test compatibility on production systems without breaking them, and does not hurt the eyes of new users; to my knowledge this was impossible previously, so I insist on my plan.

**Comment by newville** [comment]
@CasperVector 
> No, nobody asked for this; I am indeed hired at a facility, but this is a spontaneous project

Actually, last Friday, I wrote:

>> It came completely out of the blue, without context, and without warning from someone who has no history with this code. Do >> you work with or for Quantum Detectors? At some light source? I don't know.

I still do not know the actual answer.  But, I did ask.

This (epics support for xspress3) is a relatively esoteric need, serving a very small community, so it does seem reasonable that everyone actually knows each other.   Really, we are not trying to be mean, we just don't want to break everyone's xspress3 code the next time they do a `git pull`.   It doesn't seem like it should be that much work to me to not delete folders you are not using, and it is really kind of weird (like to the point of being somewhat suspicious) that you refuse to do this.  If not breaking our iocboot folders is too much to ask, then yeah, maybe we'll say "Thanks but no thanks". 

Look at it this way:  There is a small project on Github, providing control system code that serves a small, esoteric need for a community that might serve up to 1000 use cases, most of which will be at federally-funded scientific facilities.  The code history looks something like https://github.com/epics-modules/xspress3/graphs/contributors  with a total of 7 contributors and around 500 commits in the past 5 years. 

One fine day, a person who has never contributed to this project before, who is unknown to the rest of the developers, and who has not fully identified themselves submits a Pull Request to merge 100 commits, changing 400 files in the source tree.  When the response is (and here, I am quoting):
`
Thanks - that looks like a lot of work and should be very useful. But it is also kind of a lot of changes to review as a single changeset, especially coming sort of out of the blue and without any discussion or issues raised to motivate the work. 100+ commits, touching 400+ files is kind of a lot to expect to be merged.

Is it OK to view this PR as a start of a conversation about merging in all these changes? If so, would you be willing to break this into a few separate changesets?
`
the person making then makes a series of arguments about what the changes do but does not actually change any of the code in the original Pull Request.  I cannot believe that any project would entertain that Pull Request as warmly and politely as we have.

It does seem like you know what you are talking about with this code, but if you cannot comply with the request to break these changes into smaller Pull Requests that can be properly reviewed, and to not deliberately break our production iocboot scripts, then we are simply not going to trust you and will ignore all of your further messages.

**Comment by CasperVector** [comment]
I insist on my plan because I find it worth insisting on, and I have explained the rationales coherently from multiple perspectives; your responses were invariably that you "have no idea", while my average colleague can understand the same arguments with much less detailed explanation.  If you do not even attempt to understand anything that challenges your predefined religion^Wpolicy, it is then surely not my fault; by the way, this kind of behaviour is not a good sign for an open-source project.

I made this PR in the preparation phase of the paper out of pure goodwill as an open-source developer, because I find it commendable to contribute back to the community when suitable.  I said quite a few times that I am willing to wait until the paper gets online (when you will naturally know who I am), and in the worst case I am perfectly fine with my project as an independent fork.  So I do not know how you find me wanting to forcibly push changes into your repository.

Speaking of updating/splitting this PR, I have said enough before; as a matter of fact which you know but I stress here, although the PR itself is not updated, ADXspress3 is now fully functional with `iocXsp3CARS`/`iocXsp3QD` as a compatible/emulation layer.  As long as the no-`ioc*`-removal policy is in place, any sequence of PR from me will finally end up in your "having no idea" soon after the policy is questioned.  So why should I bother wasting time on spamming your issue tracker?

**Comment by newville** [comment]
I have lost hope that this conversation can possibly become productive.  Locking it now.  If you would like to make Pull Requests in the future, please heed the repeated appeal to make smaller, more focused changes that address one problem at a time.

**Pull request closed without merging**
