### PR TITLE
areaDetector2 + ROIStats Plugin support

### PR DESCRIPTION
**Pull request by newville**
This branch uses areaDetector2 and its ROIStats plugin to implement "MCA-like" ROIs for each of the detector channels.  

This is based on initial work from Matt Moore (@mdmoo1978), with some modifications by me.   The main changes include:
   
- use of ROIStats Plugin for detector ROIs (1 plugin for each detector channel, 32 ROIs each).
- a more "APS-like" build configuration.
- use of autosave (save/restore) for ROI definitions.

### CODE REVIEW

**Comment by AdamBark** [comment]
This seems quite messy. As I have made quite a few changes I would like some time to see what it makes sense to merge in and what needs changing.

**Comment by MarkRivers** [comment]
We should change this pull request so that it does not pull into the master branch in epics-modules/xspress3, but rather an APS-update branch or something.  Then it can be modified by the developers of epics-modules but won't be the master branch until we do a merge.

**Comment by newville** [comment]
@AdamBark   I'm not sure what "quite messy" means.  Can you clarify?      

It looks like your changes are also in a different account, and came after all the changes by @mdmoo1978, which I think you knew about.   I wasn't aware that you were also making changes recently.  I'd certainly like to be able to use some of your recent changes, and it would be much better to be working with a single master branch. 

I believe I cannot make a new branch in this repo, so could only make a PR to an existing branch. If an appropriate branch is made, I can remake the PR to that branch.

**Comment by MarkRivers** [comment]
I have created a new branch, APS-update.  I am closing this pull request.  Please open a new pull request on that branch,

**Comment by MarkRivers** [comment]
I have invited newville to be a developer for the xspress3 module.

**Comment by MarkRivers** [comment]
Adam has previously been invited to be a developer for the xspress3 module, but has not yet accepted the invitation.

**Comment by AdamBark** [comment]
Thanks Mark, that email got lost in my inbox at some point and it 
doesn't seem to show up on github.

On 13/05/16 14:07, Mark Rivers wrote:
>
> Adam has previously been invited to be a developer for the xspress3 
> module, but has not yet accepted the invitation.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/epics-modules/xspress3/pull/4#issuecomment-219037581>
>


-- 
This e-mail and any attachments may contain confidential, copyright and or privileged material, and are for the use of the intended addressee only. If you are not the intended addressee or an authorised recipient of the addressee please notify us of receipt by returning the e-mail and do not use, copy, retain, distribute or disclose the information in or attached to the e-mail.
Any opinions expressed within this e-mail are those of the individual and not necessarily of Diamond Light Source Ltd. 
Diamond Light Source Ltd. cannot guarantee that this e-mail or any attachments are free from viruses and we cannot accept liability for any damage which you may sustain as a result of software viruses which may be transmitted in or with the message.
Diamond Light Source Limited (company no. 4375679). Registered in England and Wales with its registered office at Diamond House, Harwell Science and Innovation Campus, Didcot, Oxfordshire, OX11 0DE, United Kingdom

**Pull request closed without merging**
