### PR TITLE
use Epics AD 2.4, include latest deadtime correction

### PR DESCRIPTION
**Pull request by newville**
This provides several improvements for Xspress3 code based on using  areaDetector 2.    This was originally done by Matthew Moore at APS, though I made some additional changes.

We've been using this branch at GSECARS for the past 3 months.   It now includes the latest deadtime correction code from Quantum Electronics.

### CODE REVIEW

**Comment by newville** [comment]
@AdamBark @NicholasRees  @mdmoo1978  I'd like to merge this into master, as I think using AD 2 is the best approach and should be the starting point for further developments.  I think no one else has been working on this code.   

I'll plan on merging next week unless I hear otherwise.

**Comment by mdmoo1978** [comment]
I'm in agreement and I haven't worked on it in a more than a year. 

Matthew D. Moore
(585) 303-5474

**Comment by ulrikpedersen** [comment]
Hi @newville 

So @NicholasRees is no longer at Diamond and I have taken on his job. Also @AdamBark is no longer at Diamond and @nbrick has taken over from him and have been working on supporting xspress3 at Diamond.

This is a huge changeset and effectively not possible to review in a short timescale. I will ask @nbrick to look over the changes.

Cheers,
Ulrik

**Comment by newville** [comment]
@ulrikpedersen @nbrick Yes, this is a very large change, replacing areaDetector 1.9 with areaDetector 2.  The changes to the driver code are not that big, but the changes to the IOCs  configurations are substantial, especially to use the ROIStats plugin.   

The current master branch was last changed in Aug 2015, and the APS-with_deadtime branch is the result of work starting around that time.    So, in some sense, the APS-with_deadtime branch represents the main development branch for the past year and a half.  FWIW, this branch is being used at 2 APS beamlines, and it works well for us.

I had heard that Adam had left, and was unsure who at DLS might be able to review these changes.   If you need more time to review or discuss these changes, that's fine with me.   To avoid diverging code bases, I think we should make sure that any further development not continue from the current master with AD 1.9, but from this branch.

**Comment by mdmoo1978** [comment]
Ulrik,

Most of these changes have been available to Diamond for more than a year. I'm made the majority of changes to make the setup AD2 compatible while I was at ANL. I haven't work at ANL since Nov. 2015. I understand this is a major change and it took Matt almost nine months to get to testing it, but I can tell you that the changes really help bring xspress3 in line with AD2. 

I would really encourage you to push the testing, since the code has been under test at ANL for more than a year. 

Matt

**Comment by newville** [comment]
@ulrikpedersen @nbrick  I haven't heard a clear "we would like to review and/or discuss this".   Please let me know soon if you would you like to review this, and what your time frame might be.

The APS winter run starts at the end of January.  I would prefer to merge this before that, so that we're running from the master branch.  If we don't merge by then, I would want to know that soon and also want to wait until late April to merge.   If anyone at DLS will be working on this code,  that could allows for divergent branches, so merging sooner would probably be better.

**Comment by newville** [comment]
@ulrikpedersen @nbrick @mdmoo1978  OK, merging this.  Very big thanks to @mdmoo1978 !!

**Pull request merged**
