### PR TITLE
added XSPRESS3 macro to the path to common folder

### PR DESCRIPTION
**Pull request by oksanagit**
On my mobile system it is convenient to have several "iocXX" folders for using in different places. The proposed change will allow to make this happen. Thanks.

### CODE REVIEW

**Comment by newville** [comment]
@oksanagit Do you have some system where the IOC boot folder and startup files are not in `$(XSPRESS3)/iocs/xspress3IOC/iocBoot/` so that the relative path for the common included files does not work?  Wouldn't that be a startup file in a different folder, not this file (`iocs/xspress3IOC/iocBoot/ioc_1Channel/st.cmd`) where the relative path will work?    Or am I not understanding something?

I would think that we'd want to keep the various N-Channel IOCs to be set up approximately the same.

**Comment by oksanagit** [comment]
@newville 
>Do you have some system where the IOC boot folder and startup files are not in $(XSPRESS3)/iocs/xspress3IOC/iocBoot/ so that the relative path for the common included files does not work? 
Yes, this is how my IOC looks like:
image

I very much like how the ioc_NChannel loads common files now. The change looks to me similar to how areaDetector/ADSomthing loads files from common folder , for example
https://github.com/areaDetector/ADPilatus/blob/6e4b6e817e21eae5def4289bf277f134dffdcd2d/iocs/pilatusIOC/iocBoot/iocPilatus/st.cmd#L42 
https://github.com/areaDetector/ADEiger/blob/46b49ab5f12dc3faf95bb810a39c78a357ffd92d/iocs/eigerIOC/iocBoot/iocEiger/st.cmd#L34

This is how my EigerIOC looks like 
image

In NSLS2 historically we deploy iocs in /epics/iocs/...  as a standard practice. 

Changing relative path to one with macro does not break the way when one runs ioc from  $(XSPRESS3)/iocs/xspress3IOC/iocBoot, but it adds value when it starts from another folder. We would benefit from  this change in every IOC I will be deploying.  I don't mind changing these several lines in every place in community iocs: ioc_x Channel, but I will be able to test only with those I have. This is not big change at all comparing to what you have done to existing and new ioc_xChannel lately. 

Why would you keep relative path?

**Comment by newville** [comment]
@oksanagit 

> Why would you keep relative path?

Well, because it is simpler and makes it clear that all the ioc_NChannel are using the same include files that are right next door. Sure, one could use an environmental variable.  That's one more thing to get wrong.  In this case, "relative paths" are actually more persistent and predictable.    For sure, they should either all be relative or all use the XSPRESS3 macro.  

As with many detector interfaces, this particular IOC really needs to run on the machine with the hardware connection to the Xspress3.  My goal is to get something that can easily be installed and run on the machines distributed with the electronics. 

If you are copying startup scripts to another location why not copy or symlink the files in `common` too?   If you are choosing to run from startup scripts outside of the xspress3/ tree, I don't see how we can really support that in this git repository.

**Comment by oksanagit** [comment]
I agree with the argument that this ioc is designed  to have  a one-to-one correspondence with hardware it talks to. I will find other ways to address my case.

**Pull request closed without merging**
