### PR TITLE
SoftwareAdvance

### PR DESCRIPTION
**Pull request by TomQD-94**
Added software advanced mode

### CODE REVIEW

**Comment by TomQD-94** [comment]
This pull request adds a PV (P):(R):FrameAdvance, that when the trigger mode is set to software will advance the frame when set to 1 and stop the frame when set to 0 allowing control from scripts etc. There is also a Manual ADV option added that uses the internal timing generator so FrameAdvance=1 will start the frame which will last a fixed time. FrameAdvance=o is still required to put the system into the correct mode to start the next frame

**Comment by newville** [comment]
@TomQD-94 Thanks!  I have not looked in detail, but hope to try this out today before merging.   

One thing that occurs to me is that it might be helpful to look at other areaDetectors and see what they call the PVs to collect 1 frame with software trigger mode.   I think that "FrameAdvance" or "ADV" might normally called "Trigger".  And, I think that some detectors may have separate modes of "a software trigger to collect N frames at fixed time interval", "a software trigger to collect 1 frame for a fixed time interval", and "a software trigger to collect 1 frame until the next software trigger or Stop".   I am not certain if there are AD conventions for all of these, but we should try to find out and follow those if we can.

Whether merging today or not, I will be going into "production mode" as X-rays come back tomorrow.  I am planning to try to use this branch but with "circBuff=0" at least to start with...

**Comment by newville** [comment]
@TomQD-94 Ah, thanks, yes I see this is a PR to master.   Do you have a preference for whether this gets merged before or after merging the `circularbuffer` branch?   There might be that need to be resolved, though I have not looked into that yet.

**Comment by TomQD-94** [comment]
Changed the name of the PV to SoftTrigger to be more recognisable to people. Changed trigger mode to Software+internal for clarity

**Comment by TomQD-94** [comment]
@newville can this be merged in as well?

**Comment by newville** [comment]
@TomQD-94 sorry for the delay on this. merging, thanks!!

**Pull request merged**
