### PR TITLE
Circularbuffer - Added circular buffer switch using variable in IOC st.cmd

### PR DESCRIPTION
**Pull request by TomQD-94**
I have added the functionality to turn on and off the circular buffer operation using a variable "CIRC_BUFFER" within the IOC st.cmd. This means you can not use more than 12216 frames when circ buffer is set to 0 and you can use as many as you like when it is set to 1. I have performed my basic testing of this operation but not yet done it with real data

### CODE REVIEW

**Comment by newville** [comment]
@TomQD-94 Sorry for the delay.  I am just getting back to having a running detector, though no real X-rays.   I did verify that #38 built and ran for me at 100 Hz and 200 Hz, but it crashes for me at 500 Hz -- have not debugged that. 

I will merge this and give it a try over the next week.  Beam comes back at the end of the month, and I'll need to run a production IOC ;)

**Comment by newville** [comment]
@TomQD-94 OK, I verified that this version goes at rates up to at least 2000 Hz in non-circular buffer mode, at least with no X-rays.  Unfortunately, the HDF5 file saver starts to drop a few frames (say ~5 out of 8000) when going faster than about 250 Hz (4 msec).   I think this is an "epics-y" thing -- it claims to not be dropping any frames, but it does in fact not write all the frames.    I think this might be related to using HDF5 "attributes" for the scaler data.  Will investigate...

**Comment by TomQD-94** [comment]
https://github.com/epics-modules/xspress3/blob/7359c7e6324730e37dabb501f2c17b691f7a3066/xspress3App/src/xspress3Epics.cpp#L1682

This line is only sending 1 frame to the scaler read, if I put FramesRemaining in then it will crash (as we saw before) I am working on seeing if this is a bug and if we can resolve it. I imagine this is where the frames start dropping.

**Comment by newville** [comment]
@TomQD-94  that's sort of interesting that it fails at reading the scalers, but not reading the mca data.  Does that make sense to you?

As I was playing with this on Friday, and got some guidance from Mark, I found that it wasn't actually the HDF5 plugin that was the problem. Turning off all the other Epics plugins and could then reliably get data at 2000 Hz, but still going much faster than that was causing some losses.   To be clear, that's all still with circular buffering off.   I'll keep looking it that....

**Pull request merged**
