### PR TITLE
Simplified Circularbuffer

### PR DESCRIPTION
**Pull request by TomQD-94**
Minimal Circular buffer that should run the same as the non-circular buffer. No longer uses the FrameRemaining technique. From my testing, this runs at the same max speed as the non-circular buffer.

### CODE REVIEW

**Comment by newville** [comment]
@TomQD-94 Thanks!  I'll merge then try it out....

**Comment by newville** [comment]
@TomQD-94  OK, this seems to work for me, though I am testing without X-rays at the moment.  

For those using non-circular buffer mode, I also made a simple change so that "ERASE" does not erase *all* frames, but only the most recently used.  This cuts the erase time down (it is about 300 msec for me with 12k frames, but is only a few msec to erase ~100 frames).  I think that erasing more than 1 frame is not actually necessary, but many people do use "ERASE" or have "EraseOnStart" set, so speeding this up will be helpful anyway.

With the recent code I found that I was seeing dropped frames (well, sort of) or just missing data.  I've set up a Struck MCS to send triggers and am asking for 8000 frames -- sort of "high but typical", and definitely a target. 

With the latest code here, but still using non-circular buffer mode (with 12000 frames max), I found that I can reliably get data at 2000 Hz (500 microsec/frame).    That is, I set up the MCS for 8000 triggers, and when it is done, the Xspress3 also shows 8000 frames read. 

To get this to work, I had to turn off some of the AD Plugins, especially those for ROIStats for the MCA Rois (and there are 48 spectra ROIS for each of the 7 elements).  For "mapping mode" where we're just streaming data, having these off is acceptable, but it means a mode switch when using these ROIs (but that implies you want to save a much smaller amount of data). 

As seen in the past, I also find that I need a short delay between hitting Acquire on the Xspress3 and actually sending triggers from the MCS.  If I wait for less than 50 msec, I end up missing a few (1 to 10 out of 8000) frames.   Waiting for 100 msec seems reliable.  This is not a huge problem but might want to be documented a bit.   In fact, I am currently waiting up to 0.5 seconds as I am assuming that an ERASE is also happening.

Saving the HDF5 data definitely does not keep up at 2kHz, but all of the frames do get written, with times that vary a bit with compression (and so might be different with non-zero data actually present).  If I collect 8000 frames at 2 kHz, the MCS and Array Counter both report being done and having all the frames at 4.1 to 4.3 seconds, but the file writing takes another 3 to 6 seconds.    So, 2 kHz looks to be "definitely working".

Between 2 and 15 kHz, the Xspress3 also appears to be working.  That is at frame times between 500 and 70 microseconds, the Xspress3 does count to all 8000 frames, and these get written to disk.  The number of frames reported when MCS finishes will be less than 8000, but 8000 frames do get written.  And the SCA0 values for each frame (after the first hot frame) for each detector channel are right to within 1 clock tick.   I interpret that to mean "working, but the display is probably not updated in time", but I think that needs real X-rays (with a reasonable count rate).

Below 70 microseconds,  the count times in the saved files show that data collection starts off OK, but then fails.   It might work to get 1000 or 2000 frames.  

So: 2 kHz is a definite yes, 10 kHz is a "probably, need to check with high count rates", and 20 kHz is "not quite". 

... I'll try with circular buffers next.

**Comment by TomQD-94** [comment]
That's great testing thank you very much. 

Addressing some of the points: 
I tested with 0 instead of 100,001 and when I didn't have the ROIs and other plugins running I sometimes had core dumps but this was when I was playing around with other things at the same time so maybe it will work better now. If people need to go over 100,000 I will look again
You should be able to run more than 16384 frames if you set MAXFRAMES and MAXDRIVERFRAMES to be higher than this, NCHANS should be unchanged. Ensure that in "common/DefineXSP3Driver.cmd" the max driver frames is not hardcoded otherwise this will prevent going to this level.
If you look at the core usage when using the ROIs there is a huge draw on resources, I haven't tested and don't have the detectors and samples ready to do full testing on if there is a sweet spot with the number of ROIs that will allow saving minimal data without having a large draw on resources slowing things down.
Waiting at the start of a scan is a little annoying and we are looking into it but Erase does just take a while. With a circular buffer, it is not technically needed as it is overwriting the data so this could be another benefit. This however could put you in a position if an error occurred you could save old data into a new frame so it is generally safer to erase first.

I think some documentation is a good idea, I am exposing another feature shortly so maybe I will write up some explanations and tips to help everyone understand what is going on.

**Comment by TomQD-94** [comment]
Additionally, when using the internal trigger i noticed an issue where the number of frames read would be less that the target say 998-999/1000 however the file saving would work ok. These frames seemed to still be in a buffer as when you start the next scan they are there, have you seen this before?

**Pull request merged**
